### ISSUE TITLE
Background blocks using the wrong IDs on 1.8

### ISSUE THREAD

**Issue by Cosmunn** [montlikadani/TeleportSigns#14]
### Describe your problem to what is
None of the 3 backgrounds blocks work on 1.8, I believe it's trying to use 1.13+ material IDs.

### Details
Plugin version: 2.3
Software (Spigot/Bukkit etc.. `/version`) version: Latest PaperSpigot 1.8.8 (build 443)

### Console error
```
[22:31:37 ERROR]: Could not pass event TeleportSignsUpdateEvent to TeleportSigns v2.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at hu.montlikadani.TeleportSigns.SignScheduler.run(SignScheduler.java:26) [TeleportSigns.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchFieldError: WHITE_STAINED_GLASS
        at hu.montlikadani.TeleportSigns.TeleportSign.chooseFromType(TeleportSign.java:192) ~[?:?]
        at hu.montlikadani.TeleportSigns.TeleportSign.updateSign(TeleportSign.java:123) ~[?:?]
        at hu.montlikadani.TeleportSigns.SignScheduler.onEvent(SignScheduler.java:37) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 12 more
```

```
[22:31:44 ERROR]: Could not pass event TeleportSignsUpdateEvent to TeleportSigns v2.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at hu.montlikadani.TeleportSigns.SignScheduler.run(SignScheduler.java:26) [TeleportSigns.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchFieldError: WHITE_WOOL
        at hu.montlikadani.TeleportSigns.TeleportSign.chooseFromType(TeleportSign.java:190) ~[?:?]
        at hu.montlikadani.TeleportSigns.TeleportSign.updateSign(TeleportSign.java:123) ~[?:?]
        at hu.montlikadani.TeleportSigns.SignScheduler.onEvent(SignScheduler.java:37) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 12 more
```

```
[22:31:50 ERROR]: Could not pass event TeleportSignsUpdateEvent to TeleportSigns v2.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at hu.montlikadani.TeleportSigns.SignScheduler.run(SignScheduler.java:26) [TeleportSigns.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchFieldError: WHITE_TERRACOTTA
        at hu.montlikadani.TeleportSigns.TeleportSign.chooseFromType(TeleportSign.java:195) ~[?:?]
        at hu.montlikadani.TeleportSigns.TeleportSign.updateSign(TeleportSign.java:123) ~[?:?]
        at hu.montlikadani.TeleportSigns.SignScheduler.onEvent(SignScheduler.java:37) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 12 more
```

### Configuration file(s)
Send the configuration file(s).
```
Don't think it's needed.
```

**Comment by montlikadani** [comment]
Because you using 1.8 version and tried to get the 1.13 materials. _Ohmygod_

**Comment by montlikadani** [comment]
It works correctly.

**Comment by Cosmunn** [comment]
That's what I thought it was, but there's no way I can set a custom material, I can only specify the type of block it's gonna use.

```
  # Defines a background of the sign.
  background:
    enable: true

    # Possible types: glass, wool, clay
    type: glass
```

If I can, please show me where. I've looked on every file and couldn't find an option.

**Comment by montlikadani** [comment]
Please send me your server plugins first.

**Comment by Cosmunn** [comment]
Here you go: `LuckPerms, AWD, JumpPads, PlaceholderAPI, ParkourRun, BigornaGM, TeleportSigns, VoidSpawn, FastAsyncWorldEdit, IPWhitelist, DynamicBungeeAuth, BCommons, VoidGenerator, BigornaUtils, Command4Bungee, BigornaShopSW, ViaVersion, Vault, MyCommand, WorldEdit, SaneEconomy, ProtocolLib, WorldGuard, Citizens, TimedRewards, PlayerLevels, ProCosmetics, HolographicDisplays, ProSkyWars, CitizensCMD, HolographicExtension`

**Comment by montlikadani** [comment]
You should remove the ViaVersion plugin, because overwrites the Bukkit versions which causing the plugin problems, such as TSigns. If you don't want, then can't fixable in this plugin or disabling the server version changing in ViaVersion. This error occurred because ViaVersion interprets Bukkit to be version 1.14 but version 1.8, so it gets confused and there are problems.

**Comment by Cosmunn** [comment]
Unfortunately I can't remove ViaVersion, but thank you for clarifying!

**Comment by montlikadani** [comment]
Ah, no .. I totally messed up .. What I wrote about ViaVersion is not valid. This is my fault and the plugin.

**Comment by montlikadani** [comment]
In this commit, should fix this issue: https://github.com/montlikadani/TeleportSigns/commit/6bd2dee9b7c5221954cb03bd09432bb264c0771d
