### ISSUE TITLE
Could not pass event ServerListPingEvent to EssentialsBackup

### ISSUE THREAD

**Issue by DexHeim** [montlikadani/TeleportSigns#17]
### Describe your problem to what is
Understand what the problem is with the plugin.

### Details
Plugin version: Latest
Software (Spigot/Bukkit etc.. `/version`) version: 1.12.2

### Console error
```
[Craft Scheduler Thread - 1210/ERROR]: Could not pass event ServerListPingEvent to EssentialsBackup v3.5.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1594]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1594]
	at hu.montlikadani.TeleportSigns.PingScheduler.lambda$0(PingScheduler.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1594]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedOperationException
	at org.bukkit.event.server.ServerListPingEvent.iterator(ServerListPingEvent.java:148) ~[patched_1.12.2.jar:git-Paper-1594]
	at DRAWXxQcTebFLnizmMrWVYbLhRDCnqfCYgGdHrWFkSTzrghYlXTGxqkwjhkRasMxTrfftWPTojaYcDjvMDRrxUuQCyJFVndubUALwRxcKymnNJGYBVnfLimzoVDAyczEVMdLPukgobrDNueyXipYRRCmLfXqvUwsfdThVdOxkhurNAIeCcxHoyhQunXHH.pSDLLFSVlebDayVSOwoAgkKxINmwNdIttubDiliaqSrrtYCMLMxeSYcPEkxPMczzlTfhPRUiGGFpmIaPUqWHAaIpzkgYUAjjycnEYPNVaMWPleQWBSDgtPhMsEYbVmcTUusXlmdfvqMKvmhVPPGcVSavQbnLkYvtnuURCrHyKQVsaSRfjsFPulyDELsORzbW.pSDLLFSVlebDayVSOwoAgkKxINmwNdIttubDiliaqSrrtYCMLMxeSYcPEkxPMczzlTfhPRUiGGFpmIaPUqWHAaIpzkgYUAjjycnEYPNVaMWPleQWBSDgtPhMsEYbVmcTUusXlmdfvqMKvmhVPPGcVSavQbnLkYvtnuURCrHyKQVsaSRfjsFPulyDELsORzbW.JoKgBJsrahTlKsBCoCamhtFJxtchKGHgkUoGLTqGogRUGhQmKaRfuSQPhMqELdDUkdAhpJOylXYGSJDovHlugTbmeJvrQzEXljFLnrBGvBMBLmWSKgGtDFPkIwKsLdFDuPdxKsVKeAkeJBviwpofxwiMLmVgdLEVmklFDYAfIaxAXJNSUNXKSUskkXgUMo.ALLATORIxDEMO(au:159) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1594]
	... 10 more
```

### Configuration file(s)
Send the configuration file(s).
```
#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#                Author, created by: montlikadani                   #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Tips]                                                            #
# - If you find a bug, send here:                                   #
# https://github.com/montlikadani/TeleportSigns/issues              #
#-----------------------------OOO-----------------------------------#

# Options
options:
  # Use external server as a hosted server?
  # If false then using internal server.
  external-server: true

  # Log plugin messages into console.
  logconsole: true

  # Sign usage time to prevent twice connect to that server.
  # This will be ignored with this permission: teleportsigns.use.nocooldown
  use-cooldown: 5

  # Sign updates time in ticks.
  # Example: 20 ticks = 1 second
  sign-updates: 200

  # How much time start the server pinging? (In seconds)
  ping-interval: 30

  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and
  # take the ping interval by one more.
  # How much time does the server pinging down? (In seconds)
  ping-timeout: 29

  # Ignoring the player sneaking when clicking on the sign.
  ignore-player-sneaking: true

  # Defines a background of the sign.
  background:
    enable: false

    # Possible types: glass, wool, clay
    type: glass

# The servers that players join.
servers:
  grief-1:
    # Server IP address and port.
    address: "51.83.53.21:25538"

    # Display name that are on the sign.
    displayname: "&6[&cValorMC&6]"
  Auth:
    # Server IP address and port.
    address: "51.83.53.21:25534"

    # Display name that are on the sign.
    displayname: "&e[&aAuth&e]"

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6[&2Teleport&eSigns&6]&7 >&a The plugin successfully enabled&6 v2.3.1&a!'
plugin-disable: '&6[&2Teleport&eSigns&6]&7 >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 5
```

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TeleportSigns/commit/60c5c6f90108a35ff9cf40b57d06545cbc5906f5

**Comment by DexHeim** [comment]
Can you post the latest assembly with the fix for this error?

**Comment by montlikadani** [comment]
Not now, because there is a bug when pinging the server is not works correctly, because it shows as server not online. So the next update may be delayed.
