### ISSUE TITLE
Sign Backgroud Causes Error

### ISSUE THREAD

**Issue by MstrTaffy** [montlikadani/TeleportSigns#8]
### Describe the bug (required)
With the config option
`Backgroud:
enable: true`
the plugin throws the below error
### Plugin version (required)
Version 2.2

### Console error (required)
```
[14:16:58 ERROR]: Could not pass event TeleportSignsUpdateEvent to TeleportSigns v2.2
java.lang.IllegalArgumentException: Material cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:143) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:138) ~[patched_1.13.2.jar:git-Paper-636]
        at hu.montlikadani.TeleportSigns.TeleportSign.updateBackground(TeleportSign.java:255) ~[?:?]
        at hu.montlikadani.TeleportSigns.TeleportSign.updateSign(TeleportSign.java:204) ~[?:?]
        at hu.montlikadani.TeleportSigns.SignScheduler.onEvent(SignScheduler.java:36) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-636]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-636]
        at hu.montlikadani.TeleportSigns.SignScheduler.run(SignScheduler.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-636]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
### Config.yml or other file
Send the config.yml or other file.
(required)
```
#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#-----------------------------OOO-----------------------------------#
# config.yml file. Plugin version: 2.2                              #
# Author, created by: montlikadani                                  #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Placeholders]                                                    #
# https://github.com/montlikadani/TeleportSigns/wiki/Placeholders   #
#                                                                   #
# [Tips]                                                            #
# - Use color coding '&' character, on this page:                   #
# http://minecraft.gamepedia.com/Formatting_codes                   #
# - If you find a bug, send here:                                   #
# https://github.com/montlikadani/TeleportSigns/issues              #
# - If the string is empty does not send the message.               #
#-----------------------------OOO-----------------------------------#

# Options
options:
  # Log plugin messages into console.
  logconsole: true

  # Sign usage time.
  # This ignoring with this permission: teleportsigns.use.nocooldown
  use-cooldown: 5

  # Sign updates in ticks. 20 ticks = 1 second.
  sign-updates: 100

  # How much time do you start the server pinging? (In seconds)
  ping-interval: 30
  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and
  # take the ping interval by one more.
  # How much time does the server pinging down? (In seconds)
  ping-timeout: 29

  # Ignoring the player sneaking when clicking on the sign.
  ignore-player-sneaking: true

  # Defines a background of the sign.
  background:
    enable: false
    # Possible types: glass, wool, clay
    type: clay

# The servers that players join.
servers:
servers:
  Pixelmon:
    # Server IP address and port.
    address: "127.0.0.1:25569"
    # Display name that are on the sign.
    displayname: "&n&l&5Pixelmon"
  
  Vanilla:
    # Server IP address and port.
    address: "127.0.0.1:25571"
    # Display name that are on the sign.
    displayname: "&n&l&5Vanilla"

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TeleportSigns plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.2&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 4

```

(optional)
```
other file
```

### Screenshots (optional)
Send a few pictures of the problem if you can.

**Comment by montlikadani** [comment]
Fixed in the latest version
